#! /bin/sh

br=$1
token=$2

user=$(whoami | sed 's/.$//g') #This sed removes the last character in string


# echo "Using Branch: $br"
# echo "Paste token:"
# read token


######WEB#####
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_ivr_restapi_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_ivr_restapi_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_customer_portal/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_customer_portal/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_external_portal/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_external_portal/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_XXXXXXXXX/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_XXXXXXXXX/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_arms/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_arms/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_benefit_engine/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_benefit_engine/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_script_engine/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_script_engine/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_wotes_application/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wotes_application/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_claim_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_claim_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_communications_indexer/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_communications_indexer/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_communications_maintenance/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_communications_maintenance/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_dq_mgr_web/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_dq_mgr_web/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_echo_sign_restapi_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_echo_sign_restapi_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_group_insurance_landing_ui/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_group_insurance_landing_ui/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_member_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_member_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_task_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_task_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_thaa_portal_services/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_thaa_portal_services/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_utility_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_utility_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_wcp_web_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wcp_web_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_application_integration/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_application_integration/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_portal_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_portal_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_reporting_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_reporting_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_rest_letter_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_rest_letter_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_XXXXXXXXX_ext/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_XXXXXXXXX_ext/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_XXXXXXXXX_ext_web_api/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_XXXXXXXXX_ext_web_api/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_restapi_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_restapi_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_XXXXXXXXX_transaction/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_XXXXXXXXX_transaction/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_tools/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_tools/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_wote_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wote_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_vendor_portal_ui/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_vendor_portal_ui/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_thaa_dis_claim_rest_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_thaa_dis_claim_rest_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_thaatm_integration/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_thaatm_integration/build 
######APP#####
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_accumulator_event_processor/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_accumulator_event_processor/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_alert_notification_batch_job/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_alert_notification_batch_job/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_appointment_reminder_batch_job/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_appointment_reminder_batch_job/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_auto_set_parms_batch/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_auto_set_parms_batch/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_ben_engine_locking_payments/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_ben_engine_locking_payments/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_com_mode_update_batch/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_com_mode_update_batch/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_common_background_process/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_common_background_process/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_disability_auto_adjudication/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_disability_auto_adjudication/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_eligibility_verification/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_eligibility_verification/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_hig_go_live_date_batch/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_hig_go_live_date_batch/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_ltd_claims_load_balancer/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_ltd_claims_load_balancer/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_member_enrollment_processor/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_member_enrollment_processor/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_monitor_file_upload/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_monitor_file_upload/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_plan_maint_notification_batch/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_plan_maint_notification_batch/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_pr_packet_creator/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_pr_packet_creator/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_queue_listener/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_queue_listener/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_scheduled_restapi_event_processor/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_scheduled_restapi_event_processor/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_scheduled_task_to_queue_processors/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_scheduled_task_to_queue_processors/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_send_email_batch_job/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_send_email_batch_job/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_stage_cci_company_data/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_stage_cci_company_data/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_staged_message_processor/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_staged_message_processor/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_stdfsm_load_balancer/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_stdfsm_load_balancer/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_suspended_payments_batch_job/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_suspended_payments_batch_job/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_task_staging_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_task_staging_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_trigger_for_text_messaging_job/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_trigger_for_text_messaging_job/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_unstructured_datamigrator/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_unstructured_datamigrator/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_update_ficaldw/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_update_ficaldw/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_user_uploaded_files_batch_job/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_user_uploaded_files_batch_job/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_vendor_portal_document_upload_batch/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_vendor_portal_document_upload_batch/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_wcp_dpp_file_notifier/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wcp_dpp_file_notifier/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_batch_print/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_batch_print/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_echo_sign_svc/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_echo_sign_svc/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_fax_status_requestor/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_fax_status_requestor/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_monitoring_service/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_monitoring_service/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_queue_processor/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_queue_processor/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_reports_auto_assignment/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_reports_auto_assignment/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_scheduling/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_scheduling/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_task_processor/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_task_processor/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_case_contact_email_process/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_case_contact_email_process/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_cm_thaa_intg_processor/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_cm_thaa_intg_processor/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_online_status_queue_processor/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_online_status_queue_processor/build 
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_mudi_processor/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_mudi_processor/build 
#web Thaa_thpa
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_thaa_thpa/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_thaa_thpa/build
#Newest _text_msg_response_job 12/23/2019, has the new path HIG not GB
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_text_msg_response_job/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_text_msg_response_job/build
#_thaa_add_features                                                                                    
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/_thaa_add_features/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_thaa_add_features/build
#gb_thaa_api_utils created 4/30/2020
curl -X POST -k --user $user:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.XXXXXXXXX/gb_thaa_api_utils/tree/'$br'"}]}' https://jenkins02.XXXXXXXXX/job/GB/job/XXXXXXXXX/job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/gb_thaa_api_utils/build
