

br='B.R.05092020'
#br='B.R.04042020_Efix2'
#br='B.R.07112020'
#br='master'

echo "Using Branch: $br"
echo "Paste token:"
read token


######WEB#####
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_ivr_restapi_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_ivr_restapi_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_customer_portal/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_customer_portal/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_external_portal/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_external_portal/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_arms/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_arms/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_benefit_engine/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_benefit_engine/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_script_engine/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_script_engine/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_wotes_application/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_wotes_application/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_claim_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_claim_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_communications_indexer/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_communications_indexer/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_communications_maintenance/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_communications_maintenance/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_dq_mgr_web/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_dq_mgr_web/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_echo_sign_restapi_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_echo_sign_restapi_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_group_insurance_landing_ui/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_group_insurance_landing_ui/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_member_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_member_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_task_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_task_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_thaa_portal_services/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_thaa_portal_services/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_utility_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_utility_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_wcp_web_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_wcp_web_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_application_integration/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_application_integration/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_portal_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_portal_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_reporting_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_reporting_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_rest_letter_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_rest_letter_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab__ext/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab__ext/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab__ext_web_api/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab__ext_web_api/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_restapi_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_restapi_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab__transaction/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab__transaction/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_tools/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_tools/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_wote_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_wote_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_vendor_portal_ui/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_vendor_portal_ui/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_thaa_dis_claim_rest_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_thaa_dis_claim_rest_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_thaatm_integration/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_thaatm_integration/build 
######APP#####
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_accumulator_event_processor/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_accumulator_event_processor/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_alert_notification_batch_job/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_alert_notification_batch_job/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_appointment_reminder_batch_job/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_appointment_reminder_batch_job/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_auto_set_parms_batch/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_auto_set_parms_batch/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_ben_engine_locking_payments/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_ben_engine_locking_payments/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_com_mode_update_batch/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_com_mode_update_batch/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_common_background_process/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_common_background_process/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_disability_auto_adjudication/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_disability_auto_adjudication/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_eligibility_verification/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_eligibility_verification/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_hig_go_live_date_batch/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_hig_go_live_date_batch/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_ltd_claims_load_balancer/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_ltd_claims_load_balancer/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_member_enrollment_processor/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_member_enrollment_processor/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_monitor_file_upload/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_monitor_file_upload/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_plan_maint_notification_batch/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_plan_maint_notification_batch/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_pr_packet_creator/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_pr_packet_creator/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_queue_listener/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_queue_listener/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_scheduled_restapi_event_processor/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_scheduled_restapi_event_processor/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_scheduled_task_to_queue_processors/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_scheduled_task_to_queue_processors/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_send_email_batch_job/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_send_email_batch_job/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_stage_cci_company_data/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_stage_cci_company_data/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_staged_message_processor/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_staged_message_processor/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_stdfsm_load_balancer/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_stdfsm_load_balancer/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_suspended_payments_batch_job/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_suspended_payments_batch_job/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_task_staging_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_task_staging_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_trigger_for_text_messaging_job/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_trigger_for_text_messaging_job/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_unstructured_datamigrator/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_unstructured_datamigrator/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_update_ficaldw/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_update_ficaldw/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_user_uploaded_files_batch_job/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_user_uploaded_files_batch_job/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_vendor_portal_document_upload_batch/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_vendor_portal_document_upload_batch/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_wcp_dpp_file_notifier/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_wcp_dpp_file_notifier/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_batch_print/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_batch_print/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_echo_sign_svc/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_echo_sign_svc/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_fax_status_requestor/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_fax_status_requestor/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_monitoring_service/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_monitoring_service/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_queue_processor/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_queue_processor/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_reports_auto_assignment/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_reports_auto_assignment/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_scheduling/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_scheduling/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_task_processor/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_task_processor/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_case_contact_email_process/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_case_contact_email_process/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_cm_thaa_intg_processor/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_cm_thaa_intg_processor/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_online_status_queue_processor/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_online_status_queue_processor/build 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_mudi_processor/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_mudi_processor/build 
#web Thaa_thpa
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com//_wkab_thaa_thpa/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_thaa_thpa/build
#Newest _wkab_text_msg_response_job 12/23/2019, has the new path HIG not 
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com/HIG/_wkab_text_msg_response_job/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WINDOWS_SERVICES/job/_wkab_text_msg_response_job/build
#_wkab_thaa_add_features                                                                                    
curl -X POST -k --user IN10421:$token --data-urlencode json='{"parameter": [{"name":"SourcePath", "value":"https://github.COMPANY.com/HIG/_wkab_thaa_add_features/tree/'$br'"}]}' https://jenkins02.COMPANY.com/job//job//job/WKAB_APPS/job/CI_INT/job/WEB_SERVICES/job/_wkab_thaa_add_feature/build
